name: Generated documentation
on: [push, pull_request]
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v22
      - run: nix develop -c bash hack/extra-demos.sh --check
      - run: nix develop -c uv run --script hack/test_update_flakes.py
      - run: nix develop -c uv run --script hack/release-extras.py --check
